-- Execute este arquivo no SQL Editor do Supabase.


create table if not exists public.users (
  uid text primary key,
  email text unique not null,
  "displayName" text,
  role text not null check (role in ('admin', 'teacher')),
  subject text,
  "createdAt" timestamptz not null default now()
);

create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  date text not null,
  "startTime" text not null,
  "endTime" text not null,
  subject text not null,
  room text,
  "teacherId" text references public.users(uid),
  "teacherName" text,
  "classGroup" text,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'absent', 'vaga')),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.labs (
  id text primary key,
  name text not null
);

create table if not exists public.lab_bookings (
  id bigint generated by default as identity primary key,
  "labId" text references public.labs(id),
  "teacherId" text references public.users(uid),
  "teacherName" text,
  date text not null,
  "startTime" text not null,
  "endTime" text not null
);

create table if not exists public.certificates (
  id bigint generated by default as identity primary key,
  "teacherId" text references public.users(uid),
  "teacherName" text,
  date text not null,
  reason text not null,
  "imageUrl" text,
  status text not null default 'pending' check (status in ('pending', 'approved')),
  "createdAt" timestamptz not null default now()
);

insert into public.labs (id, name) values
  ('info', 'Laboratório de Informática'),
  ('chem', 'Laboratório de Química')
on conflict (id) do nothing;

alter table public.users enable row level security;
alter table public.schedules enable row level security;
alter table public.labs enable row level security;
alter table public.lab_bookings enable row level security;
alter table public.certificates enable row level security;
